server:
  port: 7000

eureka:
  client:
    serviceUrl:
      #defaultZone: http://ec2-13-126-98-244.ap-south-1.compute.amazonaws.com:8082/eureka
      defaultZone: http://localhost:8082/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            #allowedOrigins: "http://lms-ng.s3-website.ap-south-1.amazonaws.com"
            allowedOrigins: "http://localhost:4002"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1.0/lms/user/**
#          filters:
#            - RewritePath=/api/v1.0/lms/user/(?<segment>.*), /$\{segment}
        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/api/v1.0/lms/courses/**