spring:
  application:
    name: eureka-discovery-service

server:
  port: 8082
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      #defaultZone: http://ec2-13-126-98-244.ap-south-1.compute.amazonaws.com:8082/eureka
      defaultZone: http://localhost:8082/eureka
  instance:
    prefer-ip-address: true